version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - FRONTEND_URL=${FRONTEND_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./app:/app/app  # For development hot-reload
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://0.0.0.0:8000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
